export const memberData = {
  clerkId: "CLsdf123",
  name: "John Doe",
  kiit_email_id: "joh33n.doe@kiit.ac.in",
  email: "ddf@gmail.com",
  personal_email_id: "john.doe@gmail.com",
  password: "hashed_passsdfdsword",
  phone: 1234567890,
  picture: "path/to/profile_picture.jpg",
  current_year: 3,
  branch: "CSE",
  roll_number: 12345,
  recruit_date: new Date(),
  type: "lead",
  position: "tech_lead",
  portfolio_website: "https://john-doe-portfolio.com",
  github_URL: "https://github.com/johndoe",
  instagram_URL: "https://www.instagram.com/johndoe/",
  linkedIn_URL: "https://www.linkedin.com/in/johndoe/",
  facebook_URL: "https://www.facebook.com/johndoe",
  behance_URL: "https://www.behance.net/johndoe",
  dribble_URL: "https://dribbble.com/johndoe",
  youtube_URL: "https://www.youtube.com/c/johndoe",
  x_URL: "https://johndoe.xyz",
  drive_URL: "https://drive.google.com/johndoe"
};